liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "imagick"

  twig:
    mode: lazy

  filter_sets:
    square_thumbnail_medium:
      filters:
        thumbnail:
          size: [300, 300]
          mode: outbound
          allow_upscale: true

    square_thumbnail_small:
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbound
          allow_upscale: true

    company_image_banner:
      filters:
        thumbnail:
          size: [600, 100]
          mode: outbound
          allow_upscale: true

    square_thumbnail_mini:
      filters:
        thumbnail:
          size: [50, 50]
          mode: outbound
          allow_upscale: true

    rectangle_thumbnail_medium:
      filters:
        thumbnail:
          size: [400, 200]
          mode: outbound
          allow_upscale: true

    rectangle_thumbnail_medium_inset:
      filters:
        thumbnail:
          size: [400, 200]
          mode: inset
          allow_upscale: true

    square_thumbnail_hmedium:
      filters:
        thumbnail:
          size: [300, 100]
          mode: outbound
          allow_upscale: true

    square_thumbnail_tiny:
      filters:
        thumbnail:
          size: [100, 100]
          mode: outbound
          allow_upscale: true

    square_thumbnail_vtiny:
      filters:
        thumbnail:
          size: [50, 50]
          mode: outbound
          allow_upscale: true

    square_thumbnail_htiny:
      filters:
        thumbnail:
          size: [150, 50]
          mode: outbound
          allow_upscale: true
